### DISCUSSION TITLE
posts/azure-artifacts-uv/

### DISCUSSION THREAD

**Discussion by giscus** [NathanVaughn/blog.nathanv.me#229] [Post Comments]
# posts/azure-artifacts-uv/

 Introduction # I love the new uv Python package/project manager and am beginning to adopt it at work. However, getting it working well with Azure Artifacts and Pipelines took a bit of fiddling so I wanted to write up my findings to supplement the official documentation.
Setup # Before creating the virtual environment, ensure you have the keyring tool installed with the artifacts-keyring package. This will require a .NET 8+ runtime.

https://blog.nathanv.me/posts/azure-artifacts-uv/

**Comment by laenan8466** [comment]
This one is great!
Locally everything is working fine, but with the Azure Pipeline I get an 
```
could not be queried due to a lack of valid authentication credentials
```

Do you face with the current UV (0.5.24) similar issues?

**Reply by NathanVaughn** [reply]
I have not, I'm afraid. The only issues I have at the moment are trying to use another git repo hosted in Azure DevOps. But pulling packages from Azure Artifacts exclusively works fine for me on 0.5.24.

**Reply by laenan8466** [reply]
Thank you! Most likely some stupid error of mine. Back to pypi in the Pipeline for now.

**Reply by laenan8466** [reply]
Found it for me! I have to use 
```yaml
   - script: uv sync
     displayName: Install dependencies
     env:
         UV_INDEX_AZURE_DEVOPS_USERNAME: "VssSessionToken"
         UV_INDEX_AZURE_DEVOPS_PASSWORD: $(System.AccessToken)
```
If I disable `UV_KEYRING_PROVIDER` it stops working for me. In the toml I keep the
```toml
[[tool.uv.index]]
name = "azure-devops"
url = "https://VssSessionToken@pkgs.dev.azure.com/{organization}/{project}/_packaging/{feed}/pypi/simple/"
default = true
```

Not sure, why this is different for me. But as long as it is working I will not complain! Thank you!
